"""카탈로그 메타 — 시트 역할 · 섹션 · 업종 · 솔루션 · 템플릿 코드 → 아키타입.

원천
- 역할 · 섹션 · 제안서 유형: winmate-kb/seed/sheet_roles.yaml + docs/scenarios/10-proposal.md 부록 A · D · E
- 업종(16) · 업종판 변형(IROLE): 10-proposal.md 부록 C
- 솔루션 11 · 전용 템플릿 설명 · 솔루션 업종 코드: 10-proposal.md 부록 B
- 템플릿 코드 · 이름 · 언제 쓰나: 'Winmate PPT' 캔버스 5개(docs/templates/source/*/canvas.json 보드 제목)
- 썸네일 kind: 부록 A(Thumb kind) — 보드에 없는 새 템플릿은 가까운 kind
"""
from __future__ import annotations

from typing import Any

SECTIONS: dict[str, dict[str, Any]] = {
    "common": {"name": "공통(표지 · 목차 · 간지 · 마무리)", "proposal_types": ["standard", "quickwin", "solution"]},
    "mi": {"name": "Market Intelligence", "proposal_types": ["standard", "solution"]},
    "vp": {"name": "Value Props", "proposal_types": ["standard", "quickwin", "solution"]},
    "birdseye": {"name": "조감도", "proposal_types": ["standard"]},
    "space_products": {"name": "공간별 제품", "proposal_types": ["standard", "quickwin"]},
    "solution": {"name": "솔루션 제안", "proposal_types": ["standard", "quickwin"]},
    "space_scenario": {"name": "공간별 가치 제공 시나리오", "proposal_types": ["solution"]},
    "cases": {"name": "유관 사례", "proposal_types": ["standard", "quickwin", "solution"]},
    "why": {"name": "Why Samsung", "proposal_types": ["standard", "solution"]},
    "spec": {"name": "제품 스펙", "proposal_types": ["standard", "quickwin"]},
    "appendix": {"name": "부록", "proposal_types": ["standard", "quickwin", "solution"]},
}

# 역할 코드 → (이름, 말하는 것, 섹션). sheet_roles.yaml 26개 + 공통 · 이미지 중심 새 유형 · 솔루션 전용.
EXTRA_ROLES: dict[str, tuple[str, str, str]] = {
    "COVER": ("표지", "누구에게 무엇을 제안하나", "common"),
    "TOC": ("목차", "무엇을 어떤 순서로", "common"),
    "DIVIDER": ("섹션 간지", "이제 이 이야기를 한다", "common"),
    "CLOSING": ("마무리", "다음 단계 · 연락처", "common"),
    "IS": ("현장 조사", "지금 이 공간을 직접 봤다", "birdseye"),
    "GN": ("생성 시안", "제안 후 모습을 미리 본다", "birdseye"),
    "MB": ("디자인 컨셉", "인테리어와 어울린다", "birdseye"),
    "UX": ("사용 장면", "누가, 언제, 어떻게 쓰나", "space_scenario"),
    "AX": ("부록", "이미지 출처 · 현장 사진", "appendix"),
    "SXI": ("솔루션 소개", "이 솔루션은 무엇이고, 언제 쓰나", "solution"),
    "SXD": ("솔루션 구성도", "어떻게 연결되고 움직이나", "solution"),
    "SXS": ("솔루션 공간 시나리오", "고객의 공간에서 언제 · 어디서 일하나", "solution"),
}

INDUSTRIES: dict[str, dict[str, str]] = {
    "FB": {"name": "외식 · 카페", "long": "외식 · 카페 프랜차이즈", "kb": "wm_fnb_cafe"},
    "RT": {"name": "리테일 · 플래그십", "long": "리테일 · 브랜드 플래그십", "kb": "wm_retail"},
    "SV": {"name": "생활 편의 · 무인 매장", "long": "생활 편의 · 무인 매장", "kb": "wm_convenience_unmanned"},
    "HT": {"name": "호텔 · 리조트", "long": "호텔 · 리조트", "kb": "wm_hotel_resort"},
    "TP": {"name": "테마파크 · 전시", "long": "테마파크 · 관광 · 전시", "kb": "wm_theme_park"},
    "VN": {"name": "공연장 · 경기장", "long": "공연장 · 경기장 · 영화관", "kb": "wm_venue"},
    "AD": {"name": "옥외 광고", "long": "옥외 · 미디어 광고", "kb": "wm_ooh"},
    "OF": {"name": "오피스", "long": "오피스 · 업무 빌딩", "kb": "wm_office"},
    "RS": {"name": "주거 분양", "long": "주거 분양 · 주택", "kb": "wm_residential_sales"},
    "ID": {"name": "인테리어 · 빌트인", "long": "인테리어 · 가구 · 빌트인 파트너", "kb": "wm_interior_partner"},
    "ED": {"name": "교육 · 캠퍼스", "long": "교육 · 캠퍼스", "kb": "wm_education"},
    "PB": {"name": "공공 · 교통", "long": "공공 · 교통 인프라", "kb": "wm_public"},
    "MD": {"name": "의료 · 요양", "long": "의료 · 요양 · 케어", "kb": "wm_medical_care"},
    "MF": {"name": "제조 · 물류 · 현장", "long": "제조 · 물류 · 현장", "kb": "wm_manufacturing_logistics"},
    "FN": {"name": "금융", "long": "금융", "kb": "wm_finance"},
    "OE": {"name": "파트너 전용 단말", "long": "파트너 전용 단말 · 에디션", "kb": "wm_partner_device"},
}
INDUSTRY_ORDER = list(INDUSTRIES)

# 업종판 변형(IROLE 원문) — 계열 → 변형 → (이름, 썸네일, 설명, 역할들)
INDUSTRY_ROLES: dict[str, dict[str, tuple[str, str, str, list[str]]]] = {
    "MI": {
        "A": ("시장 · 트렌드", "barline", "업종 시장 규모 · 동인 → 그래서 고객에게", ["MS", "TR"]),
        "B": ("고객 비즈니스 · 운영 과제", "process", "업종 사업 구조 · KPI · 운영 과제", ["CB", "CP", "IM"]),
        "C": ("사용자 여정", "journey", "사용자 · 이해관계자 여정과 개입 지점", ["US"]),
    },
    "VP": {
        "A": ("과제 → 해법 → 효과", "indVP", "업종 핵심 과제마다 삼성 해법과 효과", ["CH", "VP"]),
        "B": ("이해관계자별 가치", "persona", "업종의 결정권자 · 이용자별 가치", ["VP"]),
        "C": ("기대 효과", "hbars", "업종 KPI 전 → 후 · 투자 효과", ["EF"]),
    },
    "SS": {
        "A": ("공간 맵", "indMap", "업종 공간 전체 × 제품 · 솔루션 · 가치", ["VM", "SM"]),
        "B": ("대표 공간 장면", "scenes", "업종의 핵심 공간 한 곳의 장면", ["SS"]),
        "C": ("하루 · 동선", "indDay", "하루 · 동선 · 역할별 스윔레인", ["OP"]),
        "D": ("공간 시나리오 ④", "scenes", "대표 공간이 아닌 다른 공간 — 공간 성격에 맞는 형태(F1–F5)", ["SS"]),
        "E": ("공간 시나리오 ⑤", "scenes", "대표 공간이 아닌 다른 공간 — 공간 성격에 맞는 형태(F1–F5)", ["SS"]),
    },
}
IND_ARCH = {
    ("MI", "A"): ("market_trend", {}), ("MI", "B"): ("biz_ops", {}), ("MI", "C"): ("user_journey", {}),
    ("VP", "A"): ("chain_rows", {"image": False, "headers": ("과제", "해법", "효과")}),
    ("VP", "B"): ("personas", {"n": 3, "header": True}), ("VP", "C"): ("kpi_rows", {"n": 4}),
    ("SS", "A"): ("space_map", {"n": 7, "img_w": 560}),
    ("SS", "B"): ("hero_panel", {"img_w": 560, "n": 4, "item_style": "card_time"}),
    ("SS", "C"): ("swimlane", {"label": "역할(행) × 시각(열) — 하루 · 동선"}),
}
# 공간 시나리오 ④ ⑤ 형태(ssForms 노트) — 업종 줄 노트에서 읽는다(build.py), 못 읽으면 기본값
SS_FORMS = {
    "이용자별": ("form_users", "F1 이용자별 — 같은 공간, 세 사람이 얻는 것", "persona"),
    "문제 → 해결": ("form_problems", "F2 문제 → 해결 — 매일 생기는 문제 세 가지와 바뀌는 지표", "asis"),
    "동선 순서": ("form_path", "F3 동선 순서 — 평면 위 번호 동선, 지점마다 움직이는 솔루션", "path"),
    "운영 모드": ("form_modes", "F4 운영 모드 — 같은 기기, 시간대 · 상황별 두 모드", "image2"),
    "단계별 도입": ("form_phases", "F5 단계별 도입 — 시범 → 확대 → 전체, 단계마다 넘어가는 기준", "timeline"),
}

SOLUTIONS: dict[str, dict[str, Any]] = {
    "MGI": {"name": "MagicINFO", "desc": "설치형 사이니지 CMS", "I": "서버 · 보안 요건과 데이터 연동을 앞세울 때",
            "D": "사내 서버 · 방화벽 안에서 도는 구조", "S": "가격이 바뀌면 매장까지 몇 분 — 데이터 연동 흐름"},
    "VXT": {"name": "Samsung VXT", "desc": "클라우드 사이니지 CMS", "I": "설치 없이 바로 쓰는 구독형임을 강조할 때",
            "D": "매장엔 화면만, 나머지는 클라우드", "S": "점장이 휴대폰으로 3분 만에 교체"},
    "STP": {"name": "SmartThings Pro", "desc": "여러 사업장 IoT · 에너지", "I": "여러 매장의 기기 · 에너지를 한 화면에",
            "D": "기기는 매장에, 판단은 클라우드에", "S": "매장의 하루 — 에너지 자동화"},
    "BIT": {"name": "b.IoT", "desc": "공조 중심 빌딩 관리", "I": "공조 중심 빌딩 관리 · b.IoT / Lite 비교",
            "D": "층별 설비 → 게이트웨이 → 관리 화면", "S": "층 × 시간 — 쓰는 층만 쾌적하게"},
    "LYN": {"name": "LYNK Cloud", "desc": "호텔 객실 TV 플랫폼", "I": "투숙객 · 호텔 양쪽의 가치",
            "D": "PMS ↔ LYNK Cloud ↔ 객실 TV", "S": "체크인부터 체크아웃까지 객실 TV"},
    "KNX": {"name": "Knox Suite", "desc": "업무용 갤럭시 관리 · 보안", "I": "받는 날부터 회수까지 — 기기 수명주기",
            "D": "콘솔 하나 · 기기 속 업무 영역", "S": "새 태블릿이 매장에서 바로 일하기까지"},
    "KCP": {"name": "Knox Capture", "desc": "갤럭시로 바코드 스캔", "I": "전용 스캐너 + 단말 → 갤럭시 1대",
            "D": "스캔 값이 기존 앱까지 가는 길", "S": "입고부터 계산대까지 한 대로"},
    "DEX": {"name": "Samsung DeX", "desc": "휴대폰으로 PC 업무", "I": "휴대폰 하나로 PC 업무까지",
            "D": "연결 방식 · 업무 자원 · 보안", "S": "영업 사원의 하루, 기기는 하나"},
    "CCH": {"name": "삼성 콜드체인", "desc": "냉장 · 냉동 + 에어컨 통합 관리", "I": "성능 · 설치 · 관리 · 서비스 4 UP",
            "D": "실외기 → 쇼케이스 · 저장고 → b.IoT Cloud", "S": "한여름 오후 · 새벽에도 보관 온도 유지"},
    "HVC": {"name": "삼성 통합공조", "desc": "개별 + 중앙공조 + b.IoT", "I": "개별 + 중앙공조 = b.IoT 하나로",
            "D": "열원 → 냉수 → AHU · FCU, 개별 DVM", "S": "건물마다 다른 운전 시간을 한 화면에"},
    "SAC": {"name": "SAC 제어 시스템", "desc": "시스템에어컨 제어 · 전력량 분배", "I": "리모컨부터 BMS 연동까지 제어 단계",
            "D": "DMS · R1/R2 · F1/F2 통신 구조", "S": "임대 호실별 제어 · 전력량 분배"},
}
SOLUTION_ORDER = list(SOLUTIONS)
# 솔루션 업종 코드(부록 B IND) — 16업종과 다른 체계. aliases = 대응하는 16업종(제안, ⚠Q21)
SOLUTION_INDUSTRIES: dict[str, dict[str, Any]] = {
    "OF": {"name": "오피스", "aliases": ["OF"]}, "HT": {"name": "비즈니스 호텔", "aliases": ["HT"]},
    "RT": {"name": "매장", "aliases": ["FB", "RT", "SV"]}, "GF": {"name": "스크린골프장", "aliases": []},
    "AC": {"name": "학원", "aliases": ["ED"]}, "LG": {"name": "물류센터", "aliases": ["MF"]},
    "FD": {"name": "제조 현장", "aliases": ["MF"]}, "WH": {"name": "저온 저장시설", "aliases": ["MF"]},
}

# ── 범용 · 공통 템플릿: 코드 → (보드 파일, 역할, 아키타입, 매개변수, 썸네일 kind, 보드에 없는 이름 · 언제) ──────
# 보드 파일이 None 이면 캔버스에 보드가 없는(스펙에만 있는) 코드다.
G = dict  # 짧게

GENERIC: dict[str, dict[str, Any]] = {
    # 공통 — 표지 · 목차 · 간지 · 마무리
    "C01": G(board=("common", "L_C01.dc.html"), role="COVER", arch="cover_split", thumb="imagePanel"),
    "C02": G(board=("common", "L_C02.dc.html"), role="COVER", arch="cover_full", thumb="image"),
    "C03": G(board=("common", "L_C03.dc.html"), role="COVER", arch="cover_type", thumb="statement"),
    "C04": G(board=("common", "L_C04.dc.html"), role="TOC", arch="toc", thumb="list3"),
    "C05": G(board=("common", "L_C05.dc.html"), role="DIVIDER", arch="divider_number", thumb="bignum"),
    "C06": G(board=("common", "L_C06.dc.html"), role="DIVIDER", arch="divider_image", thumb="panelLeft"),
    "C07": G(board=("common", "L_C07.dc.html"), role="CLOSING", arch="closing", thumb="statement"),
    "C08": G(board=("common", "L_C08.dc.html"), role="COVER", arch="cover_collage", thumb="image2"),
    "C09": G(board=("common", "L_C09.dc.html"), role="COVER", arch="cover_product", thumb="imagePanel"),
    "C10": G(board=("common", "L_C10.dc.html"), role="TOC", arch="toc_thumbs", thumb="cards3img"),
    "C11": G(board=("common", "L_C11.dc.html"), role="DIVIDER", arch="divider_photo", thumb="image"),
    "C12": G(board=("common", "L_C12.dc.html"), role="CLOSING", arch="closing_image", thumb="panelLeft"),
    # MI 범용
    "MS-A": G(board=("mi", "L_MI01.dc.html"), role="MS", arch="kpi_band", p={"n": 4}, thumb="kpi4"),
    "MS-B": G(board=("mi", "L_MI02.dc.html"), role="MS", arch="chart_insights", p={"chart_kind": "bar"}, thumb="barline"),
    "MS-C": G(board=("mi", "L_MS_C.dc.html"), role="MS", arch="circles_rows", thumb="circles"),
    "MS-D": G(board=("mi", "L_MS_D.dc.html"), role="MS", arch="plot_insights", p={"n_points": 5}, thumb="bubble"),
    "MS-E": G(board=("mi", "L_MS_E.dc.html"), role="MS", arch="drivers_outlook", thumb="panel"),
    "TR-A": G(board=("mi", "L_MI06.dc.html"), role="TR", arch="timeline", p={"n": 4}, thumb="timeline"),
    "TR-B": G(board=("mi", "L_TR_B.dc.html"), role="TR", arch="trend_cards", p={"n": 3}, thumb="cards2tier"),
    "TR-C": G(board=("mi", "L_TR_C.dc.html"), role="TR", arch="plot_insights", p={"n_points": 6, "quad": True, "sub": False}, thumb="quad"),
    "CB-A": G(board=("mi", "L_MI03.dc.html"), role="CB", arch="summary_3col", thumb="summary3"),
    "CB-B": G(board=("mi", "L_CB_B.dc.html"), role="CB", arch="tree", p={"n_branch": 3, "n_leaf": 5}, thumb="tree"),
    "CB-C": G(board=("mi", "L_CB_C.dc.html"), role="CB", arch="process_pains", thumb="process"),
    "CB-D": G(board=("mi", "L_CB_D.dc.html"), role="CB", arch="swot", thumb="swot"),
    "US-A": G(board=("mi", "L_MI05.dc.html"), role="US", arch="personas", p={"n": 3}, thumb="persona"),
    "US-B": G(board=("mi", "L_US_B.dc.html"), role="US", arch="journey", p={"n": 5}, thumb="journey"),
    "US-C": G(board=("mi", "L_US_C.dc.html"), role="US", arch="donut_needs", p={"n": 4}, thumb="donut"),
    "CP-A": G(board=("mi", "L_MI04.dc.html"), role="CP", arch="table",
              p={"style": "table_hl", "band": True, "label": "비교표(행 = 비교 항목, 열 = 공급사)"}, thumb="table"),
    "CP-B": G(board=("mi", "L_CP_B.dc.html"), role="CP", arch="plot_insights", p={"n_points": 6}, thumb="scatter"),
    "CP-C": G(board=("mi", "L_CP_C.dc.html"), role="CP", arch="stacked_table", thumb="stack"),
    "IM-A": G(board=("mi", "L_IM_A.dc.html"), role="IM", arch="funnel", thumb="funnel"),
    "IM-B": G(board=("mi", "L_IM_B.dc.html"), role="IM", arch="quad_center", thumb="quadCircle"),
    # VP 범용 — 고객 과제 · 가치 제안(텍스트형) · 기대 효과
    "CH-A": G(board=("vp", "L_CH_A.dc.html"), role="CH", arch="challenge_cards", p={"n": 3}, thumb="pillars"),
    "CH-B": G(board=("vp", "L_CH_B.dc.html"), role="CH", arch="rows_arrow",
              p={"n": 4, "headers": ("운영 영역", "지금", "바라는 모습")}, thumb="asis"),
    "CH-C": G(board=("vp", "L_CH_C.dc.html"), role="CH", arch="tree",
              p={"n_branch": 3, "n_leaf": 3, "headers": ("문제", "직접 원인", "근본 원인"), "sub": True}, thumb="tree"),
    "VP-A": G(board=("vp", "L_VP01.dc.html"), role="VP", arch="rows_arrow",
              p={"n": 3, "headers": ("영역", "과제", "해결"), "sub": False}, thumb="rows"),
    "VP-B2": G(board=("vp", "L_VP02.dc.html"), role="VP", arch="pillars", p={"n": 2}, thumb="pillars", n=2),
    "VP-B3": G(board=("vp", "L_VP03.dc.html"), role="VP", arch="pillars", p={"n": 3}, thumb="pillars", n=3),
    "VP-B4": G(board=("vp", "L_VP04.dc.html"), role="VP", arch="pillars", p={"n": 4, "grid2": True}, thumb="pillars", n=4),
    "VP-C": G(board=("vp", "L_VP05.dc.html"), role="VP", arch="statement", p={"n": 3}, thumb="statement"),
    "VP-D": G(board=("vp", "L_VP_D.dc.html"), role="VP", arch="personas", p={"n": 3, "header": True}, thumb="persona"),
    "EF-A": G(board=("vp", "L_EF_A.dc.html"), role="EF", arch="kpi_rows", p={"n": 4}, thumb="hbars", n=3),
    "EF-B": G(board=("vp", "L_EF_B.dc.html"), role="EF", arch="roi", thumb="roi", n=3),
    "EF-C": G(board=("vp", "L_EF_C.dc.html"), role="EF", arch="quant_qual", thumb="split", n=3),
    # VP 이미지판(기본)
    "VP-E": G(board=("vp", "L_VP_E.dc.html"), role="VP", arch="chain_rows", p={"n": 3, "image": True}, thumb="chain", n=3),
    "VP-F2": G(board=("vp", "L_VP_F2.dc.html"), role="VP", arch="pillars", p={"n": 2, "image": True}, thumb="cards3img", n=2),
    "VP-F3": G(board=("vp", "L_VP_F.dc.html"), role="VP", arch="pillars", p={"n": 3, "image": True}, thumb="cards3img", n=3),
    "VP-F4": G(board=("vp", "L_VP_F4.dc.html"), role="VP", arch="pillars", p={"n": 4, "image": True, "grid2": True}, thumb="cards3img", n=4),
    "VP-G": G(board=("vp", "L_VP_G.dc.html"), role="VP", arch="statement", p={"n": 3, "image": True}, thumb="imagePanel", n=3),
    "VP-H": G(board=("vp", "L_VP_H.dc.html"), role="VP", arch="personas", p={"n": 4, "image": True, "header": True}, thumb="hub", n=3),
    # VP 장면판(새 레이아웃)
    "VP-I": G(board=("vp", "L_VP_I.dc.html"), role="VP", arch="image_pins",
              p={"section": "vp", "n": 4, "img_w": 520, "grade": "C", "sub": False, "image_style": "image_contain_soft"}, thumb="callouts"),
    "VP-J": G(board=("vp", "L_VP_J.dc.html"), role="VP", arch="image_pins",
              p={"section": "vp", "n": 4, "img_w": 640, "grade": "B", "sub": False}, thumb="panelLeft"),
    "VP-K": G(board=("vp", "L_VP_K.dc.html"), role="VP", arch="image_pins_wide", p={"n": 5}, thumb="pins"),
    "VP-L": G(board=("vp", "L_VP_L.dc.html"), role="VP", arch="two_images", p={"labels": ("도입 전", "도입 후")}, thumb="image2"),
    "VP-M": G(board=("vp", "L_VP_M.dc.html"), role="VP", arch="matrix",
              p={"section": "vp", "sub": False, "label": "제품(열) × 가치(행) — 열 머리에 제품 이미지 가능"}, thumb="matrix"),
    "EF-D": G(board=("vp", "L_EF_D.dc.html"), role="EF", arch="pillars", p={"n": 3, "image": True}, thumb="cards3img"),
    # VP 실사판
    "VP-N": G(board=("vp", "L_VP_N.dc.html"), role="VP", arch="hero_panel", p={"full": True, "img_w": 660, "n": 3}, thumb="imagePanel"),
    "VP-O": G(board=("vp", "L_VP_O.dc.html"), role="VP", arch="pillars", p={"n": 4, "image": True}, thumb="cards3img"),
    "VP-P": G(board=("vp", "L_VP_P.dc.html"), role="VP", arch="image_pins",
              p={"section": "vp", "n": 3, "img_w": 760, "grade": "B", "sub": False}, thumb="callouts"),
    "VP-Q": G(board=("vp", "L_VP_Q.dc.html"), role="VP", arch="hero_panel", p={"img_w": 640, "n": 3}, thumb="image"),
    "VP-R": G(board=("vp", "L_VP_R.dc.html"), role="VP", arch="path_strip", p={"section": "vp", "n": 4, "sub": False}, thumb="path"),
    "VP-S": G(board=("vp", "L_VP_S.dc.html"), role="VP", arch="two_images", p={"labels": ("고객 매장 · 지금", "도입 후")}, thumb="image2"),
    "VP-T": G(board=("vp", "L_VP_T.dc.html"), role="VP", arch="hero_panel",
              p={"img_w": 400, "n": 3, "grade": "C", "image_style": "image_contain_soft"}, thumb="imagePanel"),
    "EF-E": G(board=("vp", "L_EF_E.dc.html"), role="EF", arch="pillars", p={"n": 3, "image": True, "img_grade": "B"}, thumb="cards3img"),
    # VP 현장 질문형
    "VP-U": G(board=("vp", "L_VP_U.dc.html"), role="VP", arch="chain_rows",
              p={"n": 3, "image": True, "kw": True, "headers": ("현장 질문", "제품 · 솔루션", "핵심 가치")}, thumb="rows"),
    "VP-UC": G(board=("vp", "L_VP_UC.dc.html"), role="VP", arch="pillars", p={"n": 3, "image": True}, thumb="cards3img"),
    "VP-US": G(board=("vp", "L_VP_US.dc.html"), role="VP", arch="image_pins",
               p={"section": "vp", "n": 3, "img_w": 600, "grade": "A", "sub": False}, thumb="pins"),
    # 조감도 · 공간 전경 · 존별 포인트 · 현장 조사 · 생성 시안 · 디자인 컨셉
    "BV-A": G(board=("common", "L_BE01.dc.html"), role="BV", arch="full_image", thumb="image"),
    "BV-B": G(board=("common", "L_BE03.dc.html"), role="BV", arch="two_images",
              p={"section": "birdseye", "labels": ("주간", "야간"), "band": False}, thumb="image2"),
    "BV-C": G(board=("common", "L_BV_C.dc.html"), role="BV", arch="hero_panel",
              p={"section": "birdseye", "img_w": 760, "n": 3}, thumb="imagePanel"),
    "BV-D": G(board=("common", "L_BV_D.dc.html"), role="BV", arch="plan_grid", thumb="image2"),
    "ZP-A": G(board=("common", "L_BE02.dc.html"), role="ZP", arch="image_pins", p={"n": 4}, thumb="callouts"),
    "ZP-B": G(board=("common", "L_ZP_B.dc.html"), role="ZP", arch="plan_grid", thumb="zoom"),
    "ZP-C": G(board=("common", "L_ZP_C.dc.html"), role="ZP", arch="image_pins_wide", p={"section": "birdseye", "n": 4, "sub": True}, thumb="path"),
    "ZP-D": G(board=("common", "L_ZP_D.dc.html"), role="ZP", arch="image_pins", p={"n": 4, "img_w": 776, "sub": False}, thumb="callouts"),
    "IS-A": G(board=("common", "L_IS_A.dc.html"), role="IS", arch="image_grid", p={"section": "birdseye", "n": 6, "cols_n": 3}, thumb="grid4"),
    "IS-B": G(board=("common", "L_IS_B.dc.html"), role="IS", arch="image_pins", p={"n": 4}, thumb="callouts"),
    "GN-A": G(board=("common", "L_GN_A.dc.html"), role="GN", arch="options3", p={"section": "birdseye"}, thumb="cards3img"),
    "GN-B": G(board=("common", "L_GN_B.dc.html"), role="GN", arch="two_images",
              p={"section": "birdseye", "labels": ("현재", "제안 시안"), "band": True}, thumb="image2"),
    "GN-C": G(board=("common", "L_GN_C.dc.html"), role="GN", arch="rows_images", thumb="image2"),
    "GN-D": G(board=("common", "L_GN_D.dc.html"), role="GN", arch="options3", p={"section": "birdseye"}, thumb="cards3img"),
    "MB-A": G(board=("common", "L_MB_A.dc.html"), role="MB", arch="moodboard", thumb="grid4"),
    "MB-B": G(board=("common", "L_MB_B.dc.html"), role="MB", arch="rows_images", p={"labels": ("마감 · 소재", "어울리는 제품")}, thumb="rows"),
    "UX-A": G(board=("common", "L_UX_A.dc.html"), role="UX", arch="path_strip", p={"section": "space_scenario", "n": 5}, thumb="path"),
    "UX-B": G(board=("common", "L_UX_B.dc.html"), role="UX", arch="hero_panel",
              p={"section": "space_scenario", "img_w": 760, "n": 1}, thumb="imagePanel"),
    "UX-C": G(board=("common", "L_UX_C.dc.html"), role="UX", arch="image_grid",
              p={"section": "space_scenario", "n": 4, "cols_n": 4}, thumb="scenes"),
    # 솔루션 제안 범용
    "SA-A": G(board=("common", "L_SOL01.dc.html"), role="SA", arch="tiers", p={"n": 3}, thumb="tiers"),
    "SA-B": G(board=("common", "L_SA_B.dc.html"), role="SA", arch="hub", p={"n": 6}, thumb="hub"),
    "SA-C": G(board=("common", "L_SA_C.dc.html"), role="SA", arch="tiers", p={"n": 4, "side": 0}, thumb="layers"),
    "SA-D": G(board=("common", "L_SA_D.dc.html"), role="SA", arch="hero_panel",
              p={"section": "solution", "img_w": 560, "n": 3, "grade": "B", "item_style": "card_row_img"}, thumb="panelLeft"),
    "OP-A": G(board=("common", "L_SOL02.dc.html"), role="OP", arch="timeline", p={"section": "solution", "n": 5}, thumb="timeline"),
    "OP-B": G(board=("common", "L_OP_B.dc.html"), role="OP", arch="swimlane", p={"section": "solution"}, thumb="swimlane"),
    "OP-C": G(board=("common", "L_OP_C.dc.html"), role="OP", arch="steps_compare", thumb="stepsCompare"),
    "SF-A": G(board=("common", "L_SOL03.dc.html"), role="SF", arch="hero_panel",
              p={"section": "solution", "img_w": 560, "n": 3, "grade": "B"}, thumb="panelLeft"),
    "SF-B": G(board=("common", "L_SF_B.dc.html"), role="SF", arch="rows_arrow",
              p={"section": "solution", "n": 4, "headers": ("기능", "무엇을 하나", "고객 효과")}, thumb="featureMap"),
    "SF-C": G(board=("common", "L_SF_C.dc.html"), role="SF", arch="hero_panel",
              p={"section": "solution", "img_w": 760, "n": 3, "grade": "B"}, thumb="image"),
    "SF-D": G(board=("common", "L_SF_D.dc.html"), role="SF", arch="image_pins",
              p={"section": "solution", "n": 3, "grade": "B"}, thumb="callouts"),
    "SF-E": G(board=("common", "L_SF_E.dc.html"), role="SF", arch="image_grid",
              p={"section": "solution", "n": 8, "cols_n": 4, "grade": "B"}, thumb="grid4"),
    # 유관 사례
    "CD-A": G(board=("common", "L_CS01.dc.html"), role="CD", arch="case_story", thumb="cases"),
    "CD-B": G(board=("common", "L_CD_B.dc.html"), role="CD", arch="two_images",
              p={"section": "cases", "labels": ("도입 전", "도입 후"), "kpis": 3, "band": False}, thumb="image2kpi"),
    "CD-C": G(board=("common", "L_CD_C.dc.html"), role="CD", arch="case_numbers", thumb="bignum"),
    "CD-D": G(board=("common", "L_CD_D.dc.html"), role="CD", arch="hero_panel", p={"section": "cases", "img_w": 660, "n": 3}, thumb="image"),
    "CL-A": G(board=("common", "L_CS02.dc.html"), role="CL", arch="pillars", p={"section": "cases", "n": 2, "image": True, "img_grade": "A"}, thumb="cards2"),
    "CL-B": G(board=("common", "L_CS03.dc.html"), role="CL", arch="pillars", p={"section": "cases", "n": 3, "image": True, "img_grade": "A"}, thumb="list3"),
    "CL-C": G(board=("common", "L_CL_C.dc.html"), role="CL", arch="logo_wall", thumb="logos"),
    "CL-D": G(board=("common", "L_CL_D.dc.html"), role="CL", arch="image_grid", p={"section": "cases", "n": 6, "cols_n": 3}, thumb="cards3img"),
    # Why Samsung
    "CM-A": G(board=("common", "L_WS01.dc.html"), role="CM", arch="table",
              p={"section": "why", "style": "table_hl", "band": True, "label": "비교표(행 = 항목, 열 = 경쟁사 · 삼성 — 마지막 열 강조)"}, thumb="tableHl"),
    "CM-B": G(board=("common", "L_CM_B.dc.html"), role="CM", arch="chart_insights",
              p={"section": "why", "chart_kind": "hbar"}, thumb="hbars"),
    "CM-C": G(board=("common", "L_CM_C.dc.html"), role="CM", arch="chart_insights",
              p={"section": "why", "chart_kind": "radar"}, thumb="radar"),
    "ST-A": G(board=("common", "L_WS02.dc.html"), role="ST", arch="pillars", p={"section": "why", "n": 3}, thumb="pillars"),
    "ST-B": G(board=("common", "L_WS03.dc.html"), role="ST", arch="quad_center", p={"section": "why", "center": False}, thumb="grid4"),
    "ST-C": G(board=("common", "L_WS04.dc.html"), role="ST", arch="pillars",
              p={"section": "why", "n": 3, "style": "card_kpi_big"}, thumb="panel"),
    "ST-D": G(board=("common", "L_ST_D.dc.html"), role="ST", arch="pillars",
              p={"section": "why", "n": 3, "image": True, "img_grade": "A"}, thumb="cards3img"),
    "SV-A": G(board=("common", "L_SV_A.dc.html"), role="SV", arch="gantt", thumb="gantt"),
    "SV-B": G(board=("common", "L_SV_B.dc.html"), role="SV", arch="map_table", thumb="mapTable"),
    "SV-C": G(board=("common", "L_SV_C.dc.html"), role="SV", arch="path_strip", p={"section": "why", "n": 4}, thumb="path"),
    # 제품 스펙
    "SC-A": G(board=("common", "L_SPEC3.dc.html"), boards=["L_SPEC2.dc.html", "L_SPEC3.dc.html", "L_SPEC4.dc.html", "L_SPEC5.dc.html"],
              role="SC", arch="table", p={"section": "spec", "style": "table_spec_cols",
                                          "label": "사양 비교(행 = 항목, 열 = 제품 2–5 · 머리에 제품 이미지 가능)"},
              thumb="specTable", shape={"product_count_min": 2, "product_count_max": 5}),
    "SC-B": G(board=("common", "L_SC_B.dc.html"), role="SC", arch="table",
              p={"section": "spec", "style": "table_check", "label": "요구사항 대응표(요구 · 기준 · 제품 값 · 충족)"}, thumb="checkTable"),
    "SC-C": G(board=("common", "L_SC_C.dc.html"), role="SC", arch="pillars",
              p={"section": "spec", "n": 4, "image": True}, thumb="cards3img"),
    "SD-A": G(board=("common", "L_SPEC1.dc.html"), role="SD", arch="spec_groups", thumb="specGroups"),
    "SD-B": G(board=("common", "L_SD_B.dc.html"), role="SD", arch="drawing", thumb="drawing"),
    "SD-C": G(board=("common", "L_SD_C.dc.html"), role="SD", arch="hero_panel",
              p={"section": "spec", "img_w": 466, "n": 3, "grade": "C", "image_style": "image_contain_soft", "kpis": 3}, thumb="imagePanel"),
    # 부록
    "AX-A": G(board=("common", "L_AX_A.dc.html"), role="AX", arch="sources_table", thumb="table"),
    "AX-B": G(board=("common", "L_AX_B.dc.html"), role="AX", arch="image_grid",
              p={"section": "appendix", "n": 12, "cols_n": 4, "card": False}, thumb="grid4"),
    # 공간 시나리오 범용 — 전체 맵 · 공간마다
    "VM-A": G(board=("ss", "L_VS01.dc.html"), role="VM", arch="matrix", thumb="matrix"),
    "VM-B": G(board=("ss", "L_VS03.dc.html"), role="VM", arch="pillars",
              p={"section": "space_scenario", "n": 3, "image": True, "img_grade": "A"}, thumb="cards3img"),
    "VM-C": G(board=("ss", "L_VM_C.dc.html"), role="VM", arch="image_pins",
              p={"section": "space_scenario", "n": 5, "legend": True}, thumb="pins"),
    "VM-D": G(board=("ss", "L_VM_D.dc.html"), role="VM", arch="swimlane", p={"label": "공간(행) × 시각(열) 카드"}, thumb="swimlane"),
    "SS-A": G(board=("ss", "L_VS02.dc.html"), role="SS", arch="hero_panel",
              p={"section": "space_scenario", "img_w": 466, "n": 3, "message": False, "item_style": "card_time"}, thumb="scenes"),
    "SS-B": G(board=("ss", "L_SS_B.dc.html"), role="SS", arch="chain_cols", thumb="chain"),
    "SS-C": G(board=("ss", "L_SS_C.dc.html"), role="SS", arch="two_images",
              p={"section": "space_scenario", "labels": ("지금", "제안 후"), "chips": True}, thumb="image2"),
    # 공간별 제품 — 공간 맵 · 특수형 · 구성 · 수량
    "SM-A": G(board=("pi", "L_SP00.dc.html"), role="SM", arch="space_map", p={"n": 3}, thumb="zones"),
    "SM-B": G(board=("pi", "L_SM_B.dc.html"), role="SM", arch="matrix",
              p={"section": "space_products", "style": "table_totals", "label": "공간 × 제품 수량표(행 = 공간, 열 = 제품, 끝 = 합계)"}, thumb="qtyMatrix"),
    "SM-C": G(board=("pi", "L_SM_C.dc.html"), role="SM", arch="path_strip", p={"n": 5}, thumb="path"),
    "SM-D": G(board=("pi", "L_SM_D.dc.html"), role="SM", arch="floors", thumb="layers"),
    "SM-E": G(board=("pi", "L_SM_E.dc.html"), role="SM", arch="image_grid", p={"n": 6, "cols_n": 3}, thumb="cards3img"),
    "P-E": G(board=("pi", "L_P_E.dc.html"), role="PI", arch="drawing", p={"section": "space_products"}, thumb="drawing"),
    "P-F": G(board=("pi", "L_P_F.dc.html"), role="PI", arch="drawing", p={"section": "space_products"}, thumb="drawing"),
    "P-G": G(board=("pi", "L_P_G.dc.html"), role="PI", arch="options3", thumb="cards3img"),
    "P-H": G(board=("pi", "L_P_H.dc.html"), role="PI", arch="image_pins",
             p={"section": "space_products", "n": 4, "grade": "D", "image_style": "image_contain_soft"}, thumb="zones"),
    "P-I": G(board=("pi", "L_P_I.dc.html"), role="PI", arch="mood_full", thumb="image"),
    "P-J": G(board=("pi", "L_P_J.dc.html"), role="PI", arch="image_pins",
             p={"section": "space_products", "n": 4, "grade": "C", "img_w": 560, "image_style": "image_contain_soft"}, thumb="callouts"),
    "P-K": G(board=("pi", "L_P_K.dc.html"), role="PI", arch="rows_arrow",
             p={"section": "space_products", "n": 4, "headers": ("공간 조건", "조건", "대응 사양")}, thumb="rows"),
    "P-L": G(board=("pi", "L_P_L.dc.html"), role="PI", arch="drawing", p={"section": "space_products"}, thumb="drawing"),
    "P-M": G(board=("pi", "L_P_M.dc.html"), role="PI", arch="table",
             p={"section": "space_products", "band": True, "label": "산정 근거(항목 · 기준 · 계산 · 결과)"}, thumb="table"),
    "P-N": G(board=("pi", "L_P_N.dc.html"), role="PI", arch="rows_arrow",
             p={"section": "space_products", "n": 4, "image": True, "headers": ("위치", "기존 장비", "교체 제품")}, thumb="rows"),
    "P-O": G(board=("pi", "L_P_O.dc.html"), role="PI", arch="options3", p={"image": False}, thumb="tiers"),
    "P-P": G(board=("pi", "L_P_P.dc.html"), role="PI", arch="personas",
             p={"section": "space_products", "n": 3, "image": True}, thumb="persona"),
    "P-Q": G(board=("pi", "L_P_Q.dc.html"), role="PI", arch="personas",
             p={"section": "space_products", "n": 4, "image": True}, thumb="persona"),
    "P-R": G(board=("pi", "L_P_R.dc.html"), role="PI", arch="unit_kit", thumb="table"),
    "P-S": G(board=("pi", "L_P_S.dc.html"), role="PI", arch="hero_panel",
             p={"section": "space_products", "img_w": 400, "n": 4, "grade": "C", "image_style": "image_contain_soft"}, thumb="imagePanel"),
    "P-T": G(board=("pi", "L_P_T.dc.html"), role="PI", arch="image_grid",
             p={"n": 8, "cols_n": 4, "grade": "C"}, thumb="cards3img"),
    "BM-A": G(board=("pi", "L_BM_A.dc.html"), role="BM", arch="table",
              p={"section": "space_products", "style": "table_group", "band": True,
                 "label": "전체 구성표(구분 · 품목 · 모델 · 매장당 · 매장 수 · 총 수량 · 비고)"}, thumb="table"),
    "BM-B": G(board=("pi", "L_BM_B.dc.html"), role="BM", arch="types_cols", thumb="cards3img"),
    "BM-C": G(board=("pi", "L_BM_C.dc.html"), role="BM", arch="unit_kit", thumb="table"),
    "BM-D": G(board=("pi", "L_BM_D.dc.html"), role="BM", arch="timeline", p={"section": "space_products", "n": 3, "sub": True}, thumb="timeline"),
    "BM-E": G(board=("pi", "L_BM_E.dc.html"), role="BM", arch="map_table", p={"section": "space_products"}, thumb="mapTable"),
    # VC 조합 시리즈(공간 수 × 솔루션 수) — 역할 SS
    "VC-MAP": G(board=("ss", "L_VC_MAP.dc.html"), role="SS", arch="matrix", status="internal",
                p={"label": "조합 지도(행 = 공간 수, 열 = 솔루션 수)"}, thumb="matrix"),
    "VC-11A": G(board=("ss", "L_VC_11A.dc.html"), role="SS", arch="hero_panel",
                p={"section": "space_scenario", "img_w": 660, "n": 3}, thumb="imagePanel", shape={"space_count": 1, "solution_count": 1}),
    "VC-11B": G(board=("ss", "L_VC_11B.dc.html"), role="SS", arch="pillars",
                p={"section": "space_scenario", "n": 3, "image": True, "img_grade": "A"}, thumb="cards3img", shape={"space_count": 1, "solution_count": 1}),
    "VC-12": G(board=("ss", "L_VC_12.dc.html"), role="SS", arch="split2", p={"band": False}, thumb="split", shape={"space_count": 1, "solution_count": 2}),
    "VC-13": G(board=("ss", "L_VC_13.dc.html"), role="SS", arch="tiers",
               p={"section": "space_scenario", "n": 3, "side": 300}, thumb="layers", shape={"space_count": 1, "solution_count": 3}),
    "VC-14": G(board=("ss", "L_VC_14.dc.html"), role="SS", arch="hub", p={"section": "space_scenario", "n": 4}, thumb="hub",
               shape={"space_count": 1, "solution_count": 4}),
    "VC-1Z": G(board=("ss", "L_VC_1Z.dc.html"), role="SS", arch="space_map", p={"section": "space_scenario", "n": 4}, thumb="zones",
               shape={"space_count": 1, "zones": 4}),
    "VC-21": G(board=("ss", "L_VC_21.dc.html"), role="SS", arch="two_images",
               p={"section": "space_scenario", "labels": ("공간 1", "공간 2")}, thumb="image2", shape={"space_count": 2, "solution_count": 1}),
    "VC-22": G(board=("ss", "L_VC_22.dc.html"), role="SS", arch="two_images",
               p={"section": "space_scenario", "labels": ("공간 1", "공간 2"), "chips": True}, thumb="image2", shape={"space_count": 2, "solution_count": 2}),
    "VC-23": G(board=("ss", "L_VC_23.dc.html"), role="SS", arch="split2", p={"band": True}, thumb="split", shape={"space_count": 2, "solution_count": 3}),
    "VC-24": G(board=("ss", "L_VC_24.dc.html"), role="SS", arch="matrix", p={"label": "2열 비교(행 = 솔루션, 열 = 공간 2)"}, thumb="matrix",
               shape={"space_count": 2, "solution_count": 4}),
    "VC-31": G(board=("ss", "L_VC_31.dc.html"), role="SS", arch="path_strip", p={"section": "space_scenario", "n": 3}, thumb="path",
               shape={"space_count": 3, "solution_count": 1}),
    "VC-32": G(board=("ss", "L_VC_32.dc.html"), role="SS", arch="pillars",
               p={"section": "space_scenario", "n": 3, "image": True, "img_grade": "A", "message": True}, thumb="cards3img",
               shape={"space_count": 3, "solution_count": 2}),
    "VC-33": G(board=("ss", "L_VC_33.dc.html"), role="SS", arch="pillars",
               p={"section": "space_scenario", "n": 3, "image": True, "img_grade": "A"}, thumb="cards3img", shape={"space_count": 3, "solution_count": 3}),
    "VC-34": G(board=("ss", "L_VC_34.dc.html"), role="SS", arch="pillars",
               p={"section": "space_scenario", "n": 3, "image": True, "img_grade": "A", "message": True}, thumb="cards3img",
               shape={"space_count": 3, "solution_count": 4}),
    "VC-42": G(board=("ss", "L_VC_42.dc.html"), role="SS", arch="quad_center",
               p={"section": "space_scenario", "center": False, "sub": True}, thumb="grid4", shape={"space_count": 4, "solution_count": 2}),
    "VC-43": G(board=("ss", "L_VC_43.dc.html"), role="SS", arch="space_map",
               p={"section": "space_scenario", "n": 4, "grade": "D"}, thumb="zones", shape={"space_count": 4, "solution_count": 3}),
    "VC-64": G(board=("ss", "L_VC_64.dc.html"), role="SS", arch="matrix", p={"label": "히트맵(행 = 공간 6, 열 = 솔루션 4)"}, thumb="matrix",
               shape={"space_count": 6, "solution_count": 4}),
    "VC-N": G(board=("ss", "L_VC_N.dc.html"), role="SS", arch="tiers", p={"section": "space_scenario", "n": 3, "side": 270}, thumb="tiers",
              shape={"space_count_min": 4, "branch_types": 3}),
    "VC-J": G(board=("ss", "L_VC_J.dc.html"), role="SS", arch="swimlane", p={"label": "동선(열) × 솔루션 레인(행)"}, thumb="swimlane"),
}

# 업종 변형(같은 바탕 레이아웃) — 코드 → (바탕 코드, 업종 키(ind 값) → 16업종 코드)
VARIANTS = {
    "VP-U-HT": {"base": "VP-U", "board": ("vp", "L_VP_U_HT.dc.html"), "industry": "HT"},
    "VP-U-MD": {"base": "VP-U", "board": ("vp", "L_VP_U_MD.dc.html"), "industry": "MD"},
    "VP-UC-RT": {"base": "VP-UC", "board": ("vp", "L_VP_UC_RT.dc.html"), "industry": "RT"},
}

# 공간 제품 소개 P{n}-{v}
PI_VARIANTS = {
    "A": ("제품 이미지 중심", "제품 사진이 좋을 때 (기본)", "pA"),
    "B": ("공간 · 설치 중심", "설치 모습 · 조감도가 연결됐을 때", "pB"),
    "C": ("스펙 · 비교 중심", "수치 비교 · 라인업이 핵심일 때", "pC"),
    "D": ("강조형", "주력 제품을 지정했을 때", "pD"),
}

# 부록 A — 범용 템플릿 이름 · 언제 쓰나(보드 제목과 다를 때 스펙 원문을 우선)
SPEC_NAMES: dict[str, tuple[str, str]] = {
    "MS-A": ("핵심 수치 4", "지표는 여럿인데 연도별 추이는 없을 때"), "MS-B": ("성장 추이", "연도별 시장 규모 데이터가 있을 때"),
    "MS-C": ("TAM · SAM · SOM", "전체 중 노릴 수 있는 몫을 말할 때"), "MS-D": ("세그먼트 규모 × 성장률", "어디가 크고 빠른지, 고객 위치를 찍을 때"),
    "MS-E": ("성장 동인 → 전망", "수치는 적어도 왜 커지는지 설득할 때"), "TR-A": ("흐름 타임라인", "과거에서 다음으로 가는 방향을 보여줄 때"),
    "TR-B": ("트렌드 → 고객 시사점", "트렌드마다 '그래서 고객은'을 붙일 때"), "TR-C": ("영향도 × 시급성", "트렌드가 많아 우선순위가 필요할 때"),
    "CB-A": ("한 줄 요약 + 3단", "공개 자료로 현황을 요약할 때"), "CB-B": ("전략 목표 → 과제", "고객 전략과 이번 제안을 연결할 때"),
    "CB-C": ("운영 흐름 속 문제", "업무 단계마다 문제가 있을 때"), "CB-D": ("SWOT", "내부 · 외부 상황을 균형 있게 볼 때"),
    "US-A": ("페르소나 3", "사용자 유형이 뚜렷이 나뉠 때"), "US-B": ("고객 여정 맵", "경험 흐름 속 개입 지점을 보여줄 때"),
    "US-C": ("사용자 구성 + 니즈", "방문객 구성 비율 데이터가 있을 때"), "CP-A": ("비교표", "공급사를 항목별로 따져볼 때"),
    "CP-B": ("포지셔닝 맵", "구도와 빈자리를 한눈에 보여줄 때"), "CP-C": ("점유율 + 추이", "점유율 데이터가 있을 때"),
    "IM-A": ("발견 → 시사점 → 방향", "MI를 제안 방향 하나로 좁힐 때"), "IM-B": ("4분면 요약 + 결론", "경영진용 한 장 요약"),
    "CH-A": ("과제 3 + 영향", "문제와 그 비용을 함께 보여줄 때"), "CH-B": ("지금 → 바라는 모습", "고객이 원하는 상태가 분명할 때"),
    "CH-C": ("문제 → 근본 원인", "원인을 짚어 제안의 필요성을 만들 때"), "VP-A": ("과제 ↔ 해결 1:1", "과제마다 해법을 짝지을 때"),
    "VP-B2": ("가치 기둥 2", "Key Message 수만큼 기둥으로 세울 때"), "VP-B3": ("가치 기둥 3", "Key Message 수만큼 기둥으로 세울 때"),
    "VP-B4": ("가치 기둥 4", "Key Message 수만큼 기둥으로 세울 때"), "VP-C": ("한 문장 + 근거 3", "메시지 하나를 강하게 말할 때"),
    "VP-D": ("이해관계자별 가치", "의사결정자가 여럿일 때"), "EF-A": ("KPI 전 → 후", "개선 수치(전/후)가 있을 때"),
    "EF-B": ("투자 회수", "재무 관점으로 설득해야 할 때"), "EF-C": ("정량 + 정성 효과", "수치와 체감 효과를 함께 말할 때"),
    "BV-A": ("풀폭 전경", "조감도 한 장으로 충분할 때"), "BV-B": ("두 시점 비교", "주간/야간, 도입 전/후를 비교할 때"),
    "BV-C": ("전경 + 한 장 요약", "경영진에게 제안 전체를 요약할 때"), "ZP-A": ("번호 콜아웃", "조감도 한 장 위에 포인트를 찍을 때"),
    "ZP-B": ("존 확대 컷", "존마다 디테일 이미지가 있을 때"), "ZP-C": ("고객 동선 따라가기", "손님 동선 순서로 설명할 때"),
    "SM-A": ("존 맵 + 목록", "공간이 3곳 안팎일 때"), "SM-B": ("공간 × 제품 수량표", "공간 · 제품이 많아 교차표가 필요할 때"),
    "BM-A": ("전체 구성표", "견적 전에 전체 물량을 확정할 때"), "BM-B": ("매장 유형별 구성", "매장 규모가 여러 가지일 때"),
    "SA-A": ("계층형", "본사 → 클라우드 → 매장 구조일 때"), "SA-B": ("허브형", "솔루션 하나가 여러 기기를 묶을 때"),
    "SA-C": ("레이어 스택", "제공 범위(누가 무엇을)를 보여줄 때"), "OP-A": ("단계 타임라인", "하루 · 이벤트 흐름을 따라갈 때"),
    "OP-B": ("역할별 스윔레인", "여러 역할이 한 흐름에 관여할 때"), "OP-C": ("도입 전 → 후 업무", "업무가 얼마나 줄어드는지 보여줄 때"),
    "SF-A": ("솔루션 + 함께 쓰는 제품", "솔루션 하나를 소개할 때"), "SF-B": ("기능 → 고객 효과", "기능을 고객의 언어로 옮길 때"),
    "VM-A": ("공간 × 솔루션 매트릭스", "공간과 솔루션이 격자로 맞을 때"), "VM-B": ("공간 3개 한 장", "공간이 3곳이라 나란히 볼 때"),
    "VM-C": ("조감도 위 솔루션 핀", "조감도가 있어 위치로 보여줄 때"), "VM-D": ("하루 타임라인 × 공간", "시간에 따라 공간을 넘나들 때"),
    "SS-A": ("한 공간의 장면 3", "시간대별 장면이 있을 때"), "SS-B": ("솔루션 → 제품 → 가치", "인과(무엇이 · 무엇으로 · 어떤 가치)를 보일 때"),
    "SS-C": ("이 공간 전 → 후", "변화가 눈에 보이는 공간일 때"), "CD-A": ("과제 · 해결 · 성과", "사례를 이야기로 풀 때"),
    "CD-B": ("도입 전 → 후 사진", "전후 사진이 있을 때"), "CD-C": ("성과 수치 + 코멘트", "공개된 성과 수치가 강할 때"),
    "CL-A": ("2건 비교", "비슷한 사례 두 건을 나란히"), "CL-B": ("3건 요약", "업종이 다른 사례 세 건"),
    "CL-C": ("레퍼런스 월", "사례 수 자체가 메시지일 때"), "CM-A": ("비교표 (삼성 강조)", "항목별로 우위를 보일 때"),
    "CM-B": ("요구사항별 충족도", "고객 요구사항을 기준으로 비교할 때"), "CM-C": ("레이더 종합 비교", "여러 기준을 한 번에 종합할 때"),
    "ST-A": ("강점 3", "강점이 3개로 정리될 때"), "ST-B": ("요구 ↔ 강점 2×2", "요구사항 4개에 하나씩 답할 때"),
    "ST-C": ("강점 + 증거 수치", "검증된 수치가 있을 때"), "SV-A": ("도입 로드맵", "일정 · 단계 · 책임을 제시할 때"),
    "SV-B": ("서비스 커버리지 + SLA", "매장이 전국에 흩어져 있을 때"), "SC-A": ("사양 비교표 2~5개", "제품 간 사양 차이를 볼 때"),
    "SC-B": ("요구사항 대응표", "요구사항 충족을 증명해야 할 때"), "SD-A": ("그룹별 상세 사양", "사양 전체를 정리할 때"),
    "SD-B": ("치수 · 설치 정보", "설치 검토가 필요할 때"),
}

# sheet_roles.yaml 에서 못 읽을 때 쓰는 역할 기본값
FALLBACK_ROLES: dict[str, tuple[str, str, str]] = {
    "MS": ("시장 규모 · 성장", "이 시장은 크고 커지고 있다", "mi"), "TR": ("산업 트렌드", "업계가 이렇게 바뀐다", "mi"),
    "CB": ("고객사 비즈니스", "고객을 제대로 이해했다", "mi"), "US": ("사용자 분석", "고객의 손님과 직원을 안다", "mi"),
    "CP": ("경쟁 환경", "시장 판도는 이렇다", "mi"), "IM": ("MI 시사점", "그래서 이번 제안은", "mi"),
    "CH": ("고객 과제", "지금 이런 문제가 있다", "vp"), "VP": ("가치 제안", "우리는 이런 가치를 준다", "vp"),
    "EF": ("기대 효과", "도입하면 이만큼 좋아진다", "vp"), "BV": ("공간 전경", "완성된 공간을 미리 본다", "birdseye"),
    "ZP": ("존별 포인트", "공간마다 무엇이 달라지나", "birdseye"), "SM": ("공간 맵", "어디에 무엇을", "space_products"),
    "PI": ("공간 제품 소개", "이 공간에는 이 제품", "space_products"), "BM": ("구성 · 수량", "무엇을 몇 대", "space_products"),
    "SA": ("솔루션 구성도", "어떻게 연결되나", "solution"), "OP": ("운영 시나리오", "어떻게 쓰이나", "solution"),
    "SF": ("솔루션 상세", "이 솔루션은 무엇을 하나", "solution"), "VM": ("공간 × 솔루션 맵", "공간마다 어떤 솔루션이", "space_scenario"),
    "SS": ("공간 시나리오", "이 공간에서 이렇게 가치가 생긴다", "space_scenario"), "CD": ("사례 상세", "비슷한 고객이 이렇게 성공했다", "cases"),
    "CL": ("사례 모음", "이미 여러 곳에서 검증됐다", "cases"), "CM": ("경쟁 비교", "경쟁사보다 낫다", "why"),
    "ST": ("삼성 강점", "삼성이어야 하는 이유", "why"), "SV": ("지원 체계", "도입 후에도 책임진다", "why"),
    "SC": ("스펙 비교", "제품별 사양 차이", "spec"), "SD": ("제품 상세", "한 제품의 모든 것", "spec"),
}

# 문서 kind(표지 · 목차 · 간지 · 마무리) → 기본 템플릿
KIND_DEFAULTS = {"cover": "C01", "cover_image": "C02", "cover_text": "C03", "toc": "C04", "divider": "C05", "closing": "C07"}

CANVASES = {
    "mi": {"title": "Winmate PPT · 01 MI (업종별)", "artifact": "https://claude.ai/artifact/XnbECsMCvmCsHTsJtfeQUV"},
    "vp": {"title": "Winmate PPT · 02 Value Props (업종별)", "artifact": "https://claude.ai/artifact/V6bPV1WJhKFyJeHEYjmnhv"},
    "ss": {"title": "Winmate PPT · 03 공간별 가치 제공 시나리오 (업종별)", "artifact": "https://claude.ai/artifact/7DyZ4i11yq9sjnBP2ztEtr"},
    "pi": {"title": "Winmate PPT · 04 공간별 제품 소개", "artifact": "https://claude.ai/artifact/9mD73MY9hcPFPAavohfA7B"},
    "common": {"title": "Winmate PPT · 공통 레이아웃 · 솔루션 전용 · 분석", "artifact": "https://claude.ai/artifact/GFCVoigDttt2414bvFWDvv"},
}
